class Errors:

    def __init__(self):
        pass